(()=>{
 const audio=document.querySelector('#beats'),block=audio.closest('.audio-block');
 const player=document.createElement('div');player.className='lofi-player';player.innerHTML='<div class="lofi-art" aria-hidden="true"><div class="lofi-mascot"></div><span class="lofi-floor"></span><span class="lofi-note">♪</span></div><div class="lofi-controls"><span class="lofi-eyebrow">OFF THE CLOCK / ORIGINAL BEATS</span><div class="lofi-transport"><button type="button" class="lofi-toggle" aria-label="Play lo-fi track">▶</button><div><span class="lofi-status" role="status">Waiting for the beat.</span><div class="lofi-timing"><span class="lofi-current">0:00</span><span class="lofi-duration">–:––</span></div></div></div><label class="lofi-seek-label">Track position<input class="lofi-seek" type="range" min="0" max="100" value="0" step="0.1" aria-label="Track position" disabled></label><label class="lofi-volume-label">Volume<input class="lofi-volume" type="range" min="0" max="1" step="0.05" value="1" aria-label="Volume"></label></div>';
 block.prepend(player);audio.controls=false;audio.hidden=true;const intro=block.querySelector('label[for="beats"]');intro.hidden=false;intro.removeAttribute('for');intro.className='lofi-intro';intro.textContent="Lately, making lo-fi beats has become one of my favourite hobbies. Here’s a track I made — take a listen.";block.prepend(intro);
 const toggle=player.querySelector('.lofi-toggle'),status=player.querySelector('.lofi-status'),seek=player.querySelector('.lofi-seek');
 const time=n=>Number.isFinite(n)?Math.floor(n/60)+':'+String(Math.floor(n%60)).padStart(2,'0'):'–:––';
 function state(){const playing=!audio.paused&&!audio.ended;player.classList.toggle('is-playing',playing);toggle.textContent=playing?'Ⅱ':'▶';toggle.setAttribute('aria-label',playing?'Pause lo-fi track':'Play lo-fi track');status.textContent=playing?'In the groove.':'Waiting for the beat.';}
 toggle.addEventListener('click',async()=>{if(!audio.paused){audio.pause();return}try{status.textContent='Finding the beat…';await audio.play()}catch{status.textContent='Could not play. Try again.'}});
 ['play','pause','ended'].forEach(e=>audio.addEventListener(e,state));
 audio.addEventListener('waiting',()=>status.textContent='Loading the beat…');audio.addEventListener('playing',state);audio.addEventListener('error',()=>{state();status.textContent='Track unavailable. Please try later.'});
 function timeline(){player.querySelector('.lofi-current').textContent=time(audio.currentTime);player.querySelector('.lofi-duration').textContent=time(audio.duration);if(Number.isFinite(audio.duration)&&audio.duration>0){seek.disabled=false;seek.value=audio.currentTime/audio.duration*100;seek.setAttribute('aria-valuetext',time(audio.currentTime)+' of '+time(audio.duration));}}
 player.querySelector('.lofi-volume').addEventListener('input',event=>{audio.volume=Number(event.target.value)});audio.addEventListener('loadedmetadata',timeline);audio.addEventListener('timeupdate',timeline);seek.addEventListener('input',()=>{if(Number.isFinite(audio.duration))audio.currentTime=Number(seek.value)/100*audio.duration});
})();
